team9/collegeWebPortal/urls.py
from django.urls import path

from .views import common, professor, student

urlpatterns = [
	path('', common.index, name='index'),
    path('professor', professor.index, name='professor'),
    path('professor/courses', professor.courses, name='professor-courses'),
    path('professor/profile', professor.profile, name='professor-profile'),
    path('professor/edit_bio', professor.edit_bio, name='professor-profile-edit-bio'),
    path('professor/edit_contact', professor.edit_contact, name='professor-profile-edit-contact'),
    path('professor/edit_hour', professor.edit_hour, name='professor-profile-edit-hour'),
    path('student', student.index, name='student'),
    path('student/courses', student.courses, name='student-courses'),
    path('student/professors', student.professors, name='student-professors'),
    path('student/all_professors', student.all_professors, name='student-all-professors'),
    path('student/profile/<str:first_name>/<str:last_name>', student.list_professor_info, name='list-professors'),
    path('student/registration', student.registration, name='student-registration'),
    path('student/registration/<int:course_id>', student.sectionList, name='student-registration-course'),
    path('student/registration/section/<int:section_id>', student.sectionRegister, name='student-section-register'),
    path('student/registration/drop/<int:section_id>', student.sectionDrop, name='student-section-drop'),
    path('student/registration/process/<int:section_id>/<int:action_type>', student.processAction, name='student-registration-process'),
    path('student/registration/checkout', student.checkout, name='student-registration-checkout'),
    path('student/registration/saved', student.savedCourses, name='student-registration-saved'),
]

team9/team9/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
	path('', include('collegeWebPortal.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

team9/collegeWebPortal/models/building.py
from django.db import models


class Building(models.Model):
    code = models.CharField(max_length=8, primary_key=True)
    name = models.CharField(max_length=255)

    def __str__(self):
        return "%s" % self.name

team9/collegeWebPortal/models/course.py
from django.db import models
from .department import Department


class Course(models.Model):
	number = models.CharField(max_length=8)
	name = models.CharField(max_length=255)
	description = models.TextField(max_length=1000, blank=True)
	department = models.ForeignKey(to=Department, on_delete=models.CASCADE)
	prerequisites = models.ManyToManyField(to='Course', blank=True)
	units = models.PositiveSmallIntegerField()

	class Meta:
		unique_together = (('number', 'department'))

	def __str__(self):
		return "%s" % self.name

team9/collegeWebPortal/models/department.py
from django.db import models


class Department(models.Model):
    code = models.CharField(max_length=8, primary_key=True)
    name = models.CharField(max_length=255)

    def __str__(self):
        return "%s" % self.name

team9/collegeWebPortal/models/enrollment.py
from django.db import models
from .section import Section
from .student import Student


class Enrollment(models.Model):
    STATUS_ENROLLED = 'ER'
    STATUS_DROPPED = 'DR'
    STATUS_INCART = 'IC'
    STATUS_SAVED = 'SA'

    STATUS_CHOICES = [
        (STATUS_ENROLLED, 'Enrolled'),
        (STATUS_DROPPED, 'Dropped'),
        (STATUS_INCART, 'In Cart'),
        (STATUS_SAVED, 'Saved'),
    ]

    student = models.ForeignKey(to=Student, on_delete=models.DO_NOTHING)
    section = models.ForeignKey(to=Section, on_delete=models.DO_NOTHING)
    credits = models.PositiveSmallIntegerField(blank=True)
    grade = models.CharField(max_length=2, blank=True)
    status = models.CharField(max_length=2, choices=STATUS_CHOICES, default=STATUS_ENROLLED)

    class Meta:
        unique_together = (('student', 'section'))

team9/collegeWebPortal/models/professor.py
from django.db import models
from .department import Department
from .profile_base import ProfileBase


class Professor(ProfileBase):
    bio = models.TextField(blank=True)
    contact_info = models.CharField(max_length=255, blank=True)
    office_hours = models.CharField(max_length=255, blank=True)
    department = models.ForeignKey(to=Department, on_delete=models.PROTECT, blank=True, null=True)

team9/collegeWebPortal/models/profile_base.py
from django.db import models
from django.contrib.auth.models import User


"""
I have chosen explicitly to use a one-to-one field to the
default User model instead of using multi-table inheritance
due to some known issues with the latter
"""
class ProfileBase(models.Model):
    user = models.OneToOneField(User, primary_key=True, on_delete=models.CASCADE)

    class Meta:
        abstract = True

    def __str__(self):
        return "%s" % self.user

team9/collegeWebPortal/models/room.py
from django.db import models
from .building import Building


class Room(models.Model):
	number = models.CharField(max_length=8)
	capacity = models.PositiveSmallIntegerField()
	building = models.ForeignKey(to=Building, on_delete=models.CASCADE, related_name='building_id')

	class Meta:
		unique_together = (('number', 'building'))

	def __str__(self):
		return "%s%s" % (self.building.code, self.number)

team9/collegeWebPortal/models/section.py
from django.db import models
from .course import Course
from .professor import Professor
from .room import Room


class Section(models.Model):
	SEMESTER_SPRING = 'SP'
	SEMESTER_SUMMER = 'SU'
	SEMESTER_FALL = 'FA'
	SEMESTER_WINTER = 'WI'

	SEMESTER_CHOICES = [
		(SEMESTER_SPRING, 'Spring'),
		(SEMESTER_SUMMER, 'Summer'),
		(SEMESTER_FALL, 'Fall'),
		(SEMESTER_WINTER, 'Winter'),
	]

	STATUS_OPEN = 'O'
	STATUS_CLOSED = 'C'
	STATUS_WAITLISTED = 'W'

	STATUS_CHOICES = [
		(STATUS_OPEN, 'Open'),
		(STATUS_CLOSED, 'Closed'),
		(STATUS_WAITLISTED, 'Waitlisted'),
	]

	SCHEDULE_CHOICES = [
		('TBD', 'To Be Decided'),
		('ONL', 'Online'),
		('MON', 'Monday'),
		('TUE', 'Tuesday'),
		('WED', 'Wednesday'),
		('THU', 'Thursday'),
		('FRI', 'Friday'),
		('SAT', 'Saturday'),
		('MW', 'Monday/Wednesday'),
		('MWF', 'Monday/Wednesday/Friday'),
		('TT', 'Tuesday/Thursday'),
		('TTF', 'Tuesday/Thursday/Friday'),
		('MTWTF', 'Monday-Friday'),
	]

	course = models.ForeignKey(to=Course, on_delete=models.CASCADE)
	number = models.PositiveIntegerField()
	status = models.CharField(max_length=1, choices=STATUS_CHOICES, default=STATUS_OPEN)
	semester = models.CharField(max_length=2, choices=SEMESTER_CHOICES)
	schedule = models.CharField(max_length=5, choices=SCHEDULE_CHOICES, default='TBD')
	start_date = models.DateField()
	end_date = models.DateField()
	start_time = models.TimeField()
	end_time = models.TimeField()
	instructor = models.ForeignKey(to=Professor, on_delete=models.PROTECT)
	location = models.ForeignKey(to=Room, on_delete=models.PROTECT)

	def __str__(self):
		return "%d" % self.number

team9/collegeWebPortal/models/student.py
from django.db import models
from .profile_base import ProfileBase


class Student(ProfileBase):
	gpa = models.DecimalField(max_digits=3, decimal_places=2, blank=True)
	major_1 = models.CharField(max_length=255)
	major_2 = models.CharField(max_length=255, blank=True)
	minor = models.CharField(max_length=255, blank=True)

team9/collegeWebPortal/forms/common.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Button, Submit


class ConfirmForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Button('cancel', 'Cancel', css_class='btn-secondary', onclick='window.history.back()'))
        self.helper.add_input(Submit('submit', 'Confirm'))

team9/collegeWebPortal/views/common.py
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.http import HttpResponseRedirect
from django.urls import reverse


@login_required
def index(request):
    groups = request.user.groups

    if (groups.filter(name__exact=settings.GROUP_PROFESSORS).exists()):
        return HttpResponseRedirect(reverse('professor'))

    return HttpResponseRedirect(reverse('student'))

team9/collegeWebPortal/views/form.py
from django import forms

class SemesterForm(forms.Form):
	CHOICES = (('FA', 'Fall 2019'),('SP', 'Spring 2020'),)
	semester = forms.ChoiceField(choices=CHOICES, label='Current semester')

team9/collegeWebPortal/views/professor.py
from django.conf import settings
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from collegeWebPortal.decorators import group_required
from collegeWebPortal.models import Professor
from collegeWebPortal.models import Section
from collegeWebPortal.models import Course
from collegeWebPortal.views.form import *
from django.http import HttpResponse

@login_required
@group_required(settings.GROUP_PROFESSORS)
def index(request):
	sections = Section.objects.filter(instructor=request.user.id, semester='FA')
	return render(request, 'collegeWebPortal/professor/index.html', {'classes': sections})

@login_required
@group_required(settings.GROUP_PROFESSORS)
def courses(request):
	sections = None
	if request.method == 'POST':
		form = SemesterForm(request.POST)
		if form.is_valid():
			semester = form.cleaned_data['semester']
			sections = Section.objects.filter(instructor=request.user.id, semester=semester)
			classes = [(x, x.course) for x in sections]
			return render(request, 'collegeWebPortal/professor/courses.html', {'classes': classes, 'form': form})
		else:
			return HttpResponse("error")
	else:
		form = SemesterForm(initial={'semester':'FA'})
		sections = Section.objects.filter(instructor=request.user.id, semester='FA')
		classes = [(x, x.course) for x in sections]
		return render(request, 'collegeWebPortal/professor/courses.html', {'classes': classes, 'form': form})

@login_required
@group_required(settings.GROUP_PROFESSORS)
def profile(request):
	professor = Professor.objects.get(pk=request.user.id)
	return render(request, 'collegeWebPortal/professor/profile.html', {'usr': professor})

@login_required
@group_required(settings.GROUP_PROFESSORS)
def edit_bio(request):
	if request.method == 'POST':
		bio = request.POST.get('bio', None)
		try: 
			professor = Professor.objects.get(pk=request.user.id)
			professor.bio = bio
			professor.save()
			#return render(request, 'collegeWebPortal/professor/profile.html', {'usr': professor})
			return redirect('/professor/profile')
		except Professor.DoesNotExist:
			return HttpResponse("error")
	else:
		professor = Professor.objects.get(pk=request.user.id)
		showbioform = "True"
		return render(request, 'collegeWebPortal/professor/profile.html', {'usr': professor, 'showbioform': showbioform})


@login_required
@group_required(settings.GROUP_PROFESSORS)
def edit_contact(request):
	if request.method == 'POST':
		contact = request.POST.get('contact', None)
		try: 
			professor = Professor.objects.get(pk=request.user.id)
			professor.contact_info = contact
			professor.save()
			#return render(request, 'collegeWebPortal/professor/profile.html', {'usr': professor})
			return redirect('/professor/profile')
		except Professor.DoesNotExist:
			return HttpResponse("error")
	else:
		professor = Professor.objects.get(pk=request.user.id)
		showcontactform = "True"
		return render(request, 'collegeWebPortal/professor/profile.html', {'usr': professor, 'showcontactform': showcontactform})


@login_required
@group_required(settings.GROUP_PROFESSORS)
def edit_hour(request):
	if request.method == 'POST':
		hour = request.POST.get('hour', None)
		try: 
			professor = Professor.objects.get(pk=request.user.id)
			professor.office_hours = hour
			professor.save()
			#return render(request, 'collegeWebPortal/professor/profile.html', {'usr': professor})
			return redirect('/professor/profile')
		except Professor.DoesNotExist:
			return HttpResponse("error")
	else:
		professor = Professor.objects.get(pk=request.user.id)
		showhourform = "True"
		return render(request, 'collegeWebPortal/professor/profile.html', {'usr': professor, 'showhourform': showhourform})

team9/templates/collegeWebPortal/student/all-professors.html
{% extends 'collegeWebPortal/base_student.html' %}
{% block content %}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1>All Professors</h1>
</div>
<div>
	<table class="table table-bordered table-striped">
		<thead>
			<tr>
				<th>Name</th>
			</tr>
		</thead>
		<tbody>
			{% for professor in professor_list %}
			<tr>
				<td><a href="{% url 'list-professors' professor.user.first_name professor.user.last_name %}">{{ professor.user.first_name }} {{ professor.user.last_name }}</a></td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
</div>
{% endblock %}

team9/templates/collegeWebPortal/student/checkout.html
{% extends 'collegeWebPortal/base_student.html' %}
{% block content %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1>Checkout</h1>
</div>
{% if submitted %}
    <div class="alert alert-success alert-dismissable fade show" role="alert">
        Successfully processed your request.
    </div>
{% endif %}
<div>
    {% if sections %}
        <form method="post">
            {% csrf_token %}
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Course</th>
                        <th>Section</th>
                        <th>Semester</th>
                        <th>Schedule</th>
                        <th>Instructor</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for section in sections %}
                    <tr>
                        <td>{{ section.course.department.code }}{{ section.course.number }}</td>
                        <td>{{ section.number }}</td>
                        <td>{{ section.get_semester_display }} {{ section.start_date }} - {{ section.end_date }}</td>
                        <td>{{ section.get_schedule_display }} {{ section.start_time }} - {{ section.end_time }}</td>
                        <td>{{ section.instructor }}</td>
                        <td>{{ section.get_status_display }}</td>
                        <td>
                            {% if submitted %}
                                {% if section in status_dict.enrolled %}
                                    <strong>Enrolled</strong>
                                {% elif section in status_dict.removed %}
                                    <strong>Removed</strong>
                                {% endif %}
                            {% else %}
                                <select name="section_{{ section.id }}" class="form-control form-control-sm">
                                    <option value="register">Register</option>
                                    <option value="remove">Remove</option>
                                    <option value="none">None</option>
                                </select>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% if submitted %}
                <a href="{% url 'student-courses' %}" class="btn btn-outline-primary">Visit My Courses</a>
                <a href="{% url 'student-registration-checkout' %}" class="btn btn-outline-primary">Return to Cart</a>
            {% else %}
                <button class="btn btn-primary" type="submit">Submit</button>
            {% endif %}
        </form>
    {% else %}
        <p>You currently have no courses in your cart. Visit <a href="{% url 'student-registration' %}">Registration</a> to select courses.</p>
    {% endif %}
</div>
{% endblock %}

team9/templates/collegeWebPortal/student/courses.html
{% extends 'collegeWebPortal/base_student.html' %}
{% block content %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1>My Courses</h1>
</div>
{% if section_id %}
	<div class="alert alert-success alert-dismissable fade show" role="alert">
		<strong>Success!</strong>
		{% if dropped %}
            Section {{ section_id }} has been dropped.
        {% endif %}
	</div>
{% endif %}
<div>
    {% if sections %}
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Course</th>
                    <th>Section</th>
                    <th>Schedule</th>
                    <th>Instructor</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for section in sections %}
                <tr>
                    <td>{{ section.course.department.code }}{{ section.course.number }}</td>
                    <td>{{ section.number }}</td>
                    <td>{{ section.get_schedule_display }} {{ section.start_time }} - {{ section.end_time }}</td>
                    <td>{{ section.instructor }}</td>
                    <td>
                        <a href="{% url 'student-section-drop' section.id %}" class="btn btn-outline-danger btn-sm">Drop</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>You currently are not enrolled in any courses. Visit <a href="{% url 'student-registration' %}">Registration</a> to select courses.</p>
    {% endif %}
</div>
{% endblock %}

team9/templates/collegeWebPortal/student/index.html
{% extends 'collegeWebPortal/base_student.html' %}
{% block content %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1>Welcome, {{ user.username }}</h1>
</div>
<div>
	<h2>Class Schedule</h2>
	{% if scheduled %}
		<div class="card-deck mt-3">
		{% for section in scheduled %}
			<div class="card">
				<div class="card-body">
					<h5 class="card-title">{{ section.name }}</h5>
					<h6 class="card-subtitle mb-2 text-muted">{{ section.building }} {{ section.number }}</h6>
					<p class="card-text">{{ section.schedule }}</p>
					<p class="card-text"><small class="text-muted">{{ section.start_time }} - {{ section.end_time }}</small></p>
				</div>
			</div>
		{% endfor %}
		</div>
	{% else %}
		<ul style="list-style: none;">
			<li>You have no class yet, <a href="{% url 'student-registration' %}">register</a> for a class?</li>
		</ul>
	{% endif %}
</div>
{% endblock %}

team9/templates/collegeWebPortal/student/saved-courses.html
{% extends 'collegeWebPortal/base_student.html' %}
{% block content %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1>Saved Courses</h1>
</div>
{% if submitted %}
    <div class="alert alert-success alert-dismissable fade show" role="alert">
        Successfully processed your request.
    </div>
{% endif %}
<div>
    {% if sections %}
        <form method="post">
            {% csrf_token %}
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <td>Course</td>
                        <th>Section</th>
                        <th>Semester</th>
                        <th>Schedule</th>
                        <th>Instructor</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for section in sections %}
                    <tr>
                        <td>{{ section.course.department.code }}{{ section.course.number }}</td>
                        <td>{{ section.number }}</td>
                        <td>{{ section.get_semester_display }} {{ section.start_date }} - {{ section.end_date }}</td>
                        <td>{{ section.get_schedule_display }} {{ section.start_time }} - {{ section.end_time }}</td>
                        <td>{{ section.instructor }}</td>
                        <td>{{ section.get_status_display }}</td>
                        <td>
                            {% if submitted %}
                                {% if section in status_dict.added %}
                                    <strong>Added to Cart</strong>
                                {% elif section in status_dict.removed %}
                                    <strong>Removed</strong>
                                {% endif %}
                            {% else %}
                                <select name="section_{{ section.id }}" class="form-control form-control-sm">
                                    <option value="add">Add to Cart</option>
                                    <option value="remove">Remove</option>
                                    <option value="none">None</option>
                                </select>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% if submitted %}
                <a href="{% url 'student-registration-checkout' %}" class="btn btn-outline-primary">Go Checkout</a>
                <a href="{% url 'student-registration-saved' %}" class="btn btn-outline-primary">Return to Saved Courses</a>
            {% else %}
                <button class="btn btn-primary" type="submit">Submit</button>
            {% endif %}
        </form>
    {% else %}
        <p>You currently have no saved courses. Visit <a href="{% url 'student-registration' %}">Registration</a> to select courses.</p>
    {% endif %}
</div>
{% endblock %}

team9/templates/collegeWebPortal/student/section-drop.html
{% extends 'collegeWebPortal/base_student.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1>Drop Course</h1>
</div>
<div class="d-flex mb-3">
    <h4>Are you sure you want to drop this course?</h4>
</div>
<div>
    <table class="table table-bordered table-striped">
		<thead>
			<tr>
                <th>Course</th>
                <th>Section</th>
                <th>Semester</th>
                <th>Schedule</th>
                <th>Instructor</th>
			</tr>
		</thead>
		<tbody>
			<tr>
                <td>{{ section.course.department.code }}{{ section.course.number }}</td>
                <td>{{ section.number }}</td>
                <td>{{ section.get_semester_display }} {{ section.start_date }} - {{ section.end_date }}</td>
                <td>{{ section.get_schedule_display }} {{ section.start_time }} - {{ section.end_time }}</td>
                <td>{{ section.instructor }}</td>
			</tr>
		</tbody>
	</table>
    {% crispy form %}
</div>
{% endblock %}

team9/templates/collegeWebPortal/student/section-list.html
{% extends 'collegeWebPortal/base_student.html' %}
{% block content %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
	<h1>Registration</h1>
	<h4>{{ course.department.code }}{{ course.number }}</h4>
</div>
{% if section_id %}
	<div class="alert alert-success alert-dismissable fade show" role="alert">
		<strong>Success!</strong>
		{% if cart_added %}
			Section {{ section_id }} was added to your cart. <a href="{% url 'student-registration-checkout' %}" class="alert-link">Visit cart</a>
		{% elif enrolled %}
			You've enrolled in section {{ section_id }}.
		{% elif saved %}
			Section {{ section_id }} was added to your saved list. <a href="{% url 'student-registration-saved' %}" class="alert-link">Visit saved courses</a>
		{% endif %}
	</div>
{% endif %}
<div>
	<table class="table table-bordered table-striped">
		<thead>
			<tr>
                <th>Section</th>
                <th>Semester</th>
                <th>Schedule</th>
                <th>Instructor</th>
                <th>Location</th>
                <th>Status</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
			{% for section in sections %}
			<tr>
                <td>{{ section.number }}</td>
                <td>{{ section.get_semester_display }} {{ section.start_date }} - {{ section.end_date }}</td>
                <td>{{ section.get_schedule_display }} {{ section.start_time }} - {{ section.end_time }}</td>
                <td>{{ section.instructor }}</td>
                <td>{{ section.location }}</td>
                <td>{{ section.get_status_display }}</td>
				<td>
					<div class="dropdown">
						<button class="btn btn-sm btn-outline-primary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Select</button>
						<div class="dropdown-menu">
							{% if section in status_dict.enrolled %}
								<a class="dropdown-item disabled" href="{% url 'student-section-register' section.id %}">Register now</a>
								<a class="dropdown-item disabled" href="{% url 'student-registration-process' section.id 2 %}">Add to cart</a>
								<a class="dropdown-item disabled" href="{% url 'student-registration-process' section.id 3 %}">Save for later</a>
							{% elif section in status_dict.incart %}
								<a class="dropdown-item" href="{% url 'student-section-register' section.id %}">Register now</a>
								<a class="dropdown-item disabled" href="{% url 'student-registration-process' section.id 2 %}">Add to cart</a>
								<a class="dropdown-item disabled" href="{% url 'student-registration-process' section.id 3 %}">Save for later</a>
							{% elif section in status_dict.saved %}
								<a class="dropdown-item" href="{% url 'student-section-register' section.id %}">Register now</a>
								<a class="dropdown-item" href="{% url 'student-registration-process' section.id 2 %}">Add to cart</a>
								<a class="dropdown-item disabled" href="{% url 'student-registration-process' section.id 3 %}">Save for later</a>
							{% else %}
								<a class="dropdown-item" href="{% url 'student-section-register' section.id %}">Register now</a>
								<a class="dropdown-item" href="{% url 'student-registration-process' section.id 2 %}">Add to cart</a>
								<a class="dropdown-item" href="{% url 'student-registration-process' section.id 3 %}">Save for later</a>
							{% endif %}
						</div>
					</div>
				</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
	{% if sections.has_other_pages %}
	<ul class="pagination">
		{% if sections.has_previous %}
		<li class="page-item"><a class="page-link" href="?page={{ sections.previous_page_number }}">&laquo;</a></li>
		{% else %}
		<li class="page-item disabled"><span class="page-link">&laquo;</span></li>
		{% endif %}
		{% for i in sections.paginator.page_range %}
			{% if sections.number == i %}
			<li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
			{% else %}
			<li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
			{% endif %}
		{% endfor %}
		{% if sections.has_next %}
		<li class="page-item"><a class="page-link" href="?page={{ sections.next_page_number }}">&raquo;</a></li>
		{% else %}
		<li class="page-item disabled"><span class="page-link">&raquo;</span></li>
		{% endif %}
	</ul>
	{% endif %}
</div>
{% endblock %}

team9/templates/collegeWebPortal/student/section-register.html
{% extends 'collegeWebPortal/base_student.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1>Registration</h1>
    <h4>{{ section.course.department.code }}{{ section.course.number }}</h4>
</div>
<div class="d-flex mb-3">
    <h4>Are you sure you want to register for this course?</h4>
</div>
<div>
    <table class="table table-bordered table-striped">
		<thead>
			<tr>
                <th>Section</th>
                <th>Semester</th>
                <th>Schedule</th>
                <th>Instructor</th>
                <th>Location</th>
                <th>Status</th>
			</tr>
		</thead>
		<tbody>
			<tr>
                <td>{{ section.number }}</td>
                <td>{{ section.get_semester_display }} {{ section.start_date }} - {{ section.end_date }}</td>
                <td>{{ section.get_schedule_display }} {{ section.start_time }} - {{ section.end_time }}</td>
                <td>{{ section.instructor }}</td>
                <td>{{ section.location }}</td>
                <td>{{ section.get_status_display }}</td>
			</tr>
		</tbody>
	</table>
    {% crispy form %}
</div>
{% endblock %}